//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKySuKien
    {
        public int MaEvent { get; set; }
        public string IDSinhVien { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
