//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.DangKySuKiens = new HashSet<DangKySuKien>();
        }
    
        public int MaEnven { get; set; }
        public string TenEvent { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string ChiTiet { get; set; }
        public string MoTa { get; set; }
        public string NguoiDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> SoLuongDangKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKySuKien> DangKySuKiens { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
