//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class school_event_managementEntities : DbContext
    {
        public school_event_managementEntities()
            : base("name=school_event_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangKySuKien> DangKySuKiens { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DiaDiem> DiaDiems { get; set; }
        public virtual DbSet<EVENT> EVENTs { get; set; }
        public virtual DbSet<MaNghanh> MaNghanhs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SuKienYeuThich> SuKienYeuThiches { get; set; }
        public virtual DbSet<Vien> Viens { get; set; }
        public virtual DbSet<vw_SoChoConLai> vw_SoChoConLai { get; set; }
        public virtual DbSet<vw_UserStatsByYear> vw_UserStatsByYear { get; set; }
    }
}
