//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserStatsByYear
    {
        public string IDSinhVien { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> TongDangKyNam { get; set; }
        public Nullable<int> TongHoanThanhNam { get; set; }
        public Nullable<int> TongHuyNam { get; set; }
    }
}
